import type { BusinessProfile } from '@/types/types'

// Fuente de verdad única para el demo.
// Tanto los tools de Gemini (server) como /discover (client) usan esto.

export const MOCK_BUSINESSES: BusinessProfile[] = [
  {
    id: 'neg-001',
    businessRequestId: 'req-001',
    ownerUserId: 'usr-001',
    businessName: 'Tacos El Güero',
    businessDescription: 'Taquería tradicional en el corazón del Centro Histórico. Carnitas, suadero y pastor desde 1978. Un clásico que no puede faltar.',
    boroughCode: 'CUAUHTEMOC',
    neighborhood: 'Centro Histórico',
    latitude: 19.4326,
    longitude: -99.1332,
    locationSource: 'mock',
    operationDaysHours: 'Lun-Dom: 08:00 - 22:00',
    socialLinks: [],
    coverImageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'neg-002',
    businessRequestId: 'req-002',
    ownerUserId: 'usr-002',
    businessName: 'Café Quinto',
    businessDescription: 'Café de especialidad con single origin de Chiapas y Oaxaca. Pan artesanal horneado cada mañana en la Condesa.',
    boroughCode: 'CUAUHTEMOC',
    neighborhood: 'Condesa',
    latitude: 19.4122,
    longitude: -99.1728,
    locationSource: 'mock',
    operationDaysHours: 'Lun-Vie: 07:00 - 20:00, Sab-Dom: 08:00 - 18:00',
    socialLinks: [],
    coverImageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'neg-003',
    businessRequestId: 'req-003',
    ownerUserId: 'usr-003',
    businessName: 'Mercado de Medellín',
    businessDescription: 'Mercado tradicional con los mejores antojitos de la Roma. Tlayudas, enchiladas, frutas frescas y mucho color local.',
    boroughCode: 'CUAUHTEMOC',
    neighborhood: 'Roma Sur',
    latitude: 19.4058,
    longitude: -99.1589,
    locationSource: 'mock',
    operationDaysHours: 'Lun-Dom: 07:00 - 21:00',
    socialLinks: [],
    coverImageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'neg-004',
    businessRequestId: 'req-004',
    ownerUserId: 'usr-004',
    businessName: 'Casa de Artesanías Coyoacán',
    businessDescription: 'Artesanías mexicanas auténticas: talavera, barro negro, huipiles y joyería de plata de Taxco. Todo de productores directos.',
    boroughCode: 'COYOACAN',
    neighborhood: 'Coyoacán',
    latitude: 19.3467,
    longitude: -99.1617,
    locationSource: 'mock',
    operationDaysHours: 'Mar-Dom: 10:00 - 19:00',
    socialLinks: [],
    coverImageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'neg-005',
    businessRequestId: 'req-005',
    ownerUserId: 'usr-005',
    businessName: 'La Mezcalería Roma',
    businessDescription: 'Bar con más de 80 mezcales artesanales de Oaxaca, Guerrero y Durango. Cocina de botana con ingredientes locales de temporada.',
    boroughCode: 'CUAUHTEMOC',
    neighborhood: 'Roma Norte',
    latitude: 19.4175,
    longitude: -99.1614,
    locationSource: 'mock',
    operationDaysHours: 'Mar-Dom: 14:00 - 02:00',
    socialLinks: [],
    coverImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export function buscarNegocios(_tipo: string): BusinessProfile[] {
  return MOCK_BUSINESSES
}
